boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt.o: interrupt.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h syscall.h task.h paging.h \
  idt_handler.h lib.h terminal.h rtc.h keyboard.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h idt_handler.h interrupt.h
idt_handler.o: idt_handler.c idt_handler.h types.h lib.h i8259.h \
  syscall.h filesystem.h task.h paging.h terminal.h interrupt.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  keyboard.h rtc.h paging.h idt_handler.h idt.h syscall.h filesystem.h \
  task.h terminal.h interrupt.h pit.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h \
  syscall.h filesystem.h task.h paging.h idt_handler.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h idt_handler.h lib.h
pit.o: pit.c pit.h types.h x86_desc.h terminal.h syscall.h filesystem.h \
  task.h paging.h idt_handler.h lib.h i8259.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h terminal.h syscall.h \
  filesystem.h task.h paging.h idt_handler.h
syscall.o: syscall.c syscall.h types.h filesystem.h task.h paging.h \
  idt_handler.h lib.h terminal.h keyboard.h rtc.h x86_desc.h interrupt.h
task.o: task.c task.h types.h syscall.h filesystem.h terminal.h paging.h \
  idt_handler.h lib.h x86_desc.h
terminal.o: terminal.c keyboard.h types.h lib.h terminal.h syscall.h \
  filesystem.h task.h paging.h idt_handler.h i8259.h
